name: The CLF
favicon: null
layout_spectrum: 0.6653676859568805
typography_spectrum: 0.30518196895718575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6625805981457233
  lightness: 0.17442088550888002
  saturation: 0.14138620160520077
  rhythmicContrast: 0.3516238289885223
purpose: []
